import { apiFetch } from '../api';
import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Sparkles, Loader2, FileText, CheckCircle, RefreshCcw } from 'lucide-react';

export default function LLMReportTab({ appId, initialReport, onReportGenerated }) {
  const [reportData, setReportData] = useState(initialReport);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);

  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);
    try {
      const res = await apiFetch(`/api/apps/${appId}/generate-report`, {
        method: 'POST',
      });
      if (!res.ok) {
        throw new Error('Failed to generate report');
      }
      const data = await res.json();
      const newReportData = {
        exists: true,
        provider: data.provider,
        tone: data.tone,
        markdown: data.markdown,
        generatedAt: data.generated_at
      };
      setReportData(newReportData);
      if (onReportGenerated) onReportGenerated(newReportData);
    } catch (err) {
      setError(err.message);
    } finally {
      setIsGenerating(false);
    }
  };

  if (!reportData?.exists && !isGenerating) {
    return (
      <div className="bg-slate-800/40 border border-slate-700/50 rounded-2xl p-8 sm:p-12 text-center backdrop-blur-xl animate-fade-in">
        <div className="w-16 h-16 bg-indigo-500/10 rounded-full flex items-center justify-center mx-auto mb-6">
          <Sparkles className="w-8 h-8 text-indigo-400" />
        </div>
        <h2 className="text-xl sm:text-2xl font-bold text-slate-100 mb-3">AI Privacy Educator Brief</h2>
        <p className="text-sm sm:text-base text-slate-400 max-w-lg mx-auto mb-8">
          Generate an explainable, easy-to-understand privacy report tailored for parents and educators. 
          The current report uses a deterministic template with linked evidence. LLM summaries remain disabled until grounding is validated.
        </p>
        
        {error && (
          <div className="bg-red-500/10 text-red-400 p-3 rounded-lg text-sm mb-6 max-w-md mx-auto border border-red-500/20">
            Error: {error}
          </div>
        )}

        <button 
          onClick={handleGenerate}
          className="inline-flex items-center gap-2 px-6 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-semibold transition-all hover:scale-105 active:scale-95 shadow-lg shadow-indigo-500/25"
        >
          <Sparkles size={18} />
          Generate Educator Brief
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-800/40 border border-slate-700/50 rounded-2xl p-4 sm:p-5 backdrop-blur-xl">
        <div>
          <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            <Sparkles size={18} className="text-indigo-400" />
            AI Privacy Educator Brief
          </h2>
          {reportData?.exists && !isGenerating && (
            <p className="text-xs text-slate-400 mt-1 flex items-center gap-1.5">
              <CheckCircle size={12} className="text-emerald-400" />
              Generated by {reportData.provider} • Tone: {reportData.tone}
            </p>
          )}
        </div>
        <button 
          onClick={handleGenerate}
          disabled={isGenerating}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-700 hover:bg-slate-600 disabled:bg-slate-800 disabled:text-slate-500 text-slate-200 text-sm font-medium transition-colors w-fit"
        >
          {isGenerating ? <Loader2 size={14} className="animate-spin" /> : <RefreshCcw size={14} />}
          {isGenerating ? 'Generating...' : 'Regenerate'}
        </button>
      </div>

      <div className="bg-slate-900 border border-slate-700/50 rounded-2xl p-6 sm:p-8 relative overflow-hidden">
        {isGenerating ? (
          <div className="space-y-6 animate-pulse">
            <div className="h-8 bg-slate-800 rounded w-3/4 max-w-lg"></div>
            <div className="h-4 bg-slate-800 rounded w-full"></div>
            <div className="h-4 bg-slate-800 rounded w-5/6"></div>
            <div className="h-4 bg-slate-800 rounded w-4/6"></div>
            <div className="pt-6 space-y-3">
               <div className="h-6 bg-slate-800 rounded w-1/3"></div>
               <div className="h-4 bg-slate-800 rounded w-full"></div>
               <div className="h-4 bg-slate-800 rounded w-full"></div>
            </div>
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-indigo-500/5 to-transparent flex items-center justify-center">
              <div className="flex flex-col items-center gap-3">
                <Loader2 className="w-10 h-10 text-indigo-500 animate-spin" />
                <span className="text-indigo-400 font-medium">Synthesizing Multimodal Evidence...</span>
              </div>
            </div>
          </div>
        ) : (
          <div className="prose prose-invert prose-indigo max-w-none">
            <ReactMarkdown>{reportData.markdown}</ReactMarkdown>
          </div>
        )}
      </div>
    </div>
  );
}
